name: Build

on: 
  push:
    branches: 
      - '*'
      - '*/**'
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'Acknowledgments.md'
      - '.github/workflows/release.yml'

jobs:
  native:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Build Dir
        id: cache-build-dir
        uses: actions/cache@v3
        with:
          path: out
          key: ${{ runner.os }}-out

      - name: Build and Test
        run: |
          cmake -E make_directory out
          cmake -S . -B out -DCMAKE_BUILD_TYPE=Debug -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"
          cmake --build out --target run-library-test --config Debug
  
  windows-x86:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Build Dir
        id: cache-build-dir
        uses: actions/cache@v3
        with:
          path: out
          key: windows-x86-out

      - name: Build and Test
        run: |
          cmake -E make_directory out
          cmake -S . -B out -A Win32
          cmake --build out --target run-library-test --config Debug

  windows-arm64:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Build Dir
        id: cache-build-dir
        uses: actions/cache@v3
        with:
          path: out
          key: windows-arm64-out

      - name: Build and Test
        run: |
          cmake -E make_directory out
          cmake -S . -B out -A ARM64
          cmake --build out --target library-test --config Debug

  emscripten:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Build Dir
        id: cache-build-dir
        uses: actions/cache@v3
        with:
          path: out
          key: ${{ runner.os }}-emscripten-out

      - name: Setup EMSDK
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: 3.1.26
          actions-cache-folder: 'emsdk-cache'

      - name: Build and Test
        run: |
          cmake -E make_directory out
          cmake -S . -B out -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=$EMSDK/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake
          cmake --build out --target test --config Debug

      
          